### ISSUE TITLE
Hope to add an example to use Nginx as reversed proxy.

### ISSUE THREAD

**Issue by Akagi201** [EOSIO/patroneos#18]
Nginx is used a lot in my company.

**Comment by ericiles** [comment]
In our advanced example, we chose HAProxy to demonstrate the set up. There should be no issues with substituting any reverse proxy for HAProxy, so long as it is forwarding traffic to Patroneos (Filter Mode). You just need to make sure the X-Forwarded-For header is sent to Patroneos so that it can properly log the client's IP address, instead of that of the reverse proxy.
