### ISSUE TITLE
Run patroneos on boot

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/patroneos#49]
It would be useful to register patroneos as a service to be auto started on boot.

**Comment by NorseGaud** [comment]
Go doesn't natively provide a reliable way to daemonize itself. Fortunately, there are a few online guides which offer some guidance on setting this up. I like: https://fabianlee.org/2017/05/21/golang-running-a-go-binary-as-a-systemd-service-on-ubuntu-16-04/

Might need a few modifications to patroneos, but otherwise looks promising.

**Comment by bitcoiners** [comment]
I ended up creating a systemd service for it.
---
[Unit]
Description=Patroneos service
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/patroneos
ExecStart=/opt/patroneos/dist/patroneosd config.json

[Install]
WantedBy=multi-user.target
